spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1/project?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true

    dbcp2:
      #获取连接时候验证
      test-on-borrow: true
      #验证连接的有效性
      test-while-idle: true
      #指定连接池等待连接返回的最大等待时间，毫秒单位.
      max-wait-millis: 60000
      #指定必须保持连接的最小值
      min-idle: 5


 # Redis数据库索引（默认为0）
  redis:
    database: 0
    # Redis服务器地址
    host: localhost
    #Redis服务器连接端口
    port: 6379
    #Redis服务器密码
    password: 123456
    # 连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 60000ms




mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


## Memcache 配置 ##
memcache:
  ip: 127.0.0.1
  port: 11211

